use Auditing



-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [Project]
CREATE TABLE [Project]
(
 [ProjectId]       int NOT NULL PRIMARY KEY ([ProjectId] ASC),
 [ProjectName]     varchar(255) NOT NULL ,
 [ProjectImageURL] varchar(255) NOT NULL ,
 [ClientName]      varchar(255) NOT NULL ,
 [Manager]         varchar(255) NOT NULL ,
);
GO



-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [Audit]
CREATE TABLE [Audit]
(
 [AuditId]             int NOT NULL PRIMARY KEY ([AuditId] ASC),
 [AuditDate]           date NOT NULL ,
 [InternalAuditorName] varchar(255) NOT NULL ,
 [ExternalAuditorName] varchar(255) NOT NULL ,
 [ProjectId]           int NOT NULL FOREIGN KEY ([ProjectId])  REFERENCES [Project]([ProjectId]),
 [Score]               float NOT NULL 
);
GO






-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [Domain]
CREATE TABLE [Domain]
(
 [DomainId]      int NOT NULL PRIMARY KEY ([DomainId] ASC),
 [DomainName]    varchar(255) NOT NULL ,
 [DomainNameURL] varchar(255) NOT NULL ,
 [Category]      varchar(255) NOT NULL ,

);
GO




-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [Questions]
CREATE TABLE [Questions]
(
 [QuestionId]  int NOT NULL PRIMARY KEY ([QuestionId] ASC),
 [Description] varchar(255) NOT NULL ,
 [IsMandatory] bit NOT NULL ,
 [Category]    varchar(255) NOT NULL ,
 [DomainId]    int NOT NULL FOREIGN KEY ([DomainId])  REFERENCES [Domain]([DomainId]),
);
GO



-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [AuditDetails]
CREATE TABLE [AuditDetails]
(
 [AuditDetailsId] int NOT NULL PRIMARY KEY CLUSTERED ([AuditDetailsId] ASC),
 [AuditName]        VARCHAR(100)   NOT NULL FOREIGN KEY ([AuditId])  REFERENCES [Audit]([AuditId]),
 [AuditId]        int NOT NULL ,
 [QuestionId]     int NOT NULL FOREIGN KEY ([QuestionId])  REFERENCES [Questions]([QuestionId]),
 [Response]       bit NOT NULL ,
 [Comment]        varchar(255) NOT NULL ,
 [Rating]         int NOT NULL ,
);
GO





-- ********************* SqlDBM: Microsoft SQL Server ********************
-- * Generated by SqlDBM: ProjectAudit, v2 by karthiknaidu6309@gmail.com *


-- ************************************** [ProjectDomainBridge]
CREATE TABLE [ProjectDomainBridge]
(
 [ProjectDomainBridgeId] int NOT NULL PRIMARY KEY ([ProjectDomainBridgeId] ASC),
 [ProjectId]             int NOT NULL FOREIGN KEY ([ProjectId])  REFERENCES [Project]([ProjectId]),
 [DomainId]              int NOT NULL FOREIGN KEY ([DomainId])  REFERENCES [Domain]([DomainId]),

);
GO




-- ************************************** [Users]
CREATE TABLE [Users]
(
 [EmpId] VARCHAR(100) NOT NULL PRIMARY KEY ([EmpId] ASC),
 [EmpName]             VARCHAR(100),
 [Mail]              VARCHAR(100),
 [ReportingManager] VARCHAR(50)
);
GO




-- ************************************** [UsersbRIDGE]
CREATE TABLE [UserBridge]
(
 [UserBridgeId] INT IDENTITY PRIMARY KEY,
 [ProjectId]             INT,
 [UserId]              VARCHAR(100)
);
GO




-- ************************************** [Users]
CREATE TABLE [AuditBridge]
(
 [AuditBridgeId] INT IDENTITY PRIMARY KEY,
 [AuditId]             VARCHAR(100),
 [UserId]              VARCHAR(100)
);
GO

